### ISSUE TITLE
Treat blank preRelease the same as null?

### ISSUE THREAD

**Issue by peterfigure** [swiftzer/semver#11]
`SemVer(1, 2, 3).copy(preRelease = "")`  will throw an Exception.. seems a bit unreasonable?

how about 

`if (!preRelease.isNullOrBlank()) require(preRelease.matches(Regex("""[\dA-z\-]+(?:\.[\dA-z\-]+)*"""))) { "Pre-release version is not valid" }`

**Comment by ericksli** [comment]
I think it is better to not allowing empty string because it would be strange when calling the getter of `preRelease` would be null but previously it was successsful to set the value as empty string.

Also, it makes the field more complicated to use as you need to consider 3 cases: null, empty string, non-empty string.
